name: CI

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.17.0'
      - name: Install dependencies
        run: npm install
      - name: Run prettier
        run: npm run prettier:fix
      - name: Run eslint
        run: npm run lint:fix

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.17.0'
      - name: Install dependencies
        run: npm install
      - name: Run e2e tests
        run: npm run playwright

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.17.0'
      - name: Install dependencies
        run: npm install
      - name: build production project
        run: npm run build
